### ISSUE TITLE
Disable output to console in non-development environment

### ISSUE THREAD

**Issue by innomaxx** [dalisoft/nanoexpress#43]
Here is my fake code.

![image](https://user-images.githubusercontent.com/40697586/66051176-20564f00-e537-11e9-9f85-1a0adda055d8.png)

In production environment it still writes to console, which is unacceptable for me. 

![image](https://user-images.githubusercontent.com/40697586/66050556-1bdd6680-e536-11e9-8bd8-a6afc2fc907e.png)

In package's source code there are no runtime environment checks present.

![image](https://user-images.githubusercontent.com/40697586/66051390-8cd14e00-e537-11e9-9f73-5d73d567699c.png)

Can you provide some `process.env.DEBUG` or `process.env.NODE_ENV` checks?

**Comment by dalisoft** [comment]
Hi dear friend. 

I am sorry, because such of error or mismatching your exception about project (because of my fail). 

I currently does not have as i work on full-time job. I don’t think for me nothing bad is from logging just start with ms and address, but as you know, each peoples mind differs from other. 

Maybe, can you submit PR if possible. Sorry again. 

Thanks for using this library and wish you all the best

**Comment by innomaxx** [comment]
Already submitted PR, please check
